version: '3.9'
services:
db:
image: postgres:16
container_name: c360_db
environment:
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
POSTGRES_USER: ${POSTGRES_USER}
POSTGRES_DB: ${POSTGRES_DB}
ports:
- "${POSTGRES_PORT}:5432"
volumes:
- db_data:/var/lib/postgresql/data
adminer:
image: adminer
container_name: c360_adminer
restart: always
ports:
- "8080:8080"
depends_on:
- db
volumes:
db_data: